// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtP0VMlMFpnduHDjU9B830Jox5248Z7Q',
    appId: '1:170068570586:web:1d44d844bbd9411b6c90e3',
    messagingSenderId: '170068570586',
    projectId: 'frozen-note',
    authDomain: 'frozen-note.firebaseapp.com',
    storageBucket: 'frozen-note.appspot.com',
    measurementId: 'G-VF1D4QREYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nCCgOLWvulXvpn0yfcyMQw5DfOoAlGY',
    appId: '1:170068570586:android:d0e4ae13ae9645676c90e3',
    messagingSenderId: '170068570586',
    projectId: 'frozen-note',
    storageBucket: 'frozen-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsRjnc4EHn0V3pauYhWflFGdre2Y82mU',
    appId: '1:170068570586:ios:690537b1b1bbb7936c90e3',
    messagingSenderId: '170068570586',
    projectId: 'frozen-note',
    storageBucket: 'frozen-note.appspot.com',
    androidClientId: '170068570586-6bjq5pjgu9mld41b4835tdovnnb72dds.apps.googleusercontent.com',
    iosClientId: '170068570586-1lo42eagotr5min48tpfbg25c5ufgq01.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFrozenNote',
  );

}